from __future__ import annotations

from typing import Optional

import numpy as np

from ... import MjData, MjModel, MjrRect, MjrContext, MjvCamera, MjvOption, MjvScene, mjtFontScale

class Renderer:
    def __init__(self, model: MjModel, height: int = ..., width: int = ..., max_geom: int = ..., font_scale: mjtFontScale = ...) -> None: ...
    @property
    def model(self) -> MjModel: ...
    @property
    def scene(self) -> MjvScene: ...
    @property
    def height(self) -> int: ...
    @property
    def width(self) -> int: ...
    def enable_depth_rendering(self) -> None: ...
    def disable_depth_rendering(self) -> None: ...
    def enable_segmentation_rendering(self) -> None: ...
    def disable_segmentation_rendering(self) -> None: ...
    def render(self, *, out: Optional[np.ndarray] = ...) -> np.ndarray: ...
    def update_scene(self, data: MjData, camera: int | str | MjvCamera = ..., scene_option: MjvOption | None = ...) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Renderer: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
