project: artefacts/go2-mujoco
version: 0.1.0

jobs:
  basic_test:
    type: test
    timeout: 20 # minutes
    package:
      docker:
        build:
          dockerfile: Dockerfile
    runtime:
      framework: null
      simulator: mujoco
      
    scenarios:
      settings:
        - name: "test movement"
          pytest_file: tests/test_demo.py
          output_dirs: ["output"]
          params:
            v_forward:      [0.2, 0.4]
            v_lateral:      [0.0]
            rotation_speed: [2.0]
