from __future__ import annotations

from collections.abc import Sequence
from enum import IntEnum
from typing import IO, Any, Literal, TypeAlias, overload

import numpy as np
import numpy.typing as npt

FloatArray: TypeAlias = npt.NDArray[np.float64]
Float32Array: TypeAlias = npt.NDArray[np.float32]
IntArray: TypeAlias = npt.NDArray[np.int_]
UInt8Array: TypeAlias = npt.NDArray[np.uint8]
BoolArray: TypeAlias = npt.NDArray[np.bool_]
AnyArray: TypeAlias = npt.NDArray[Any]
Int32Array = npt.NDArray[np.int32]

MjStruct: TypeAlias = Any

class FatalError(RuntimeError): ...
class UnexpectedError(RuntimeError): ...

class mjtObj(IntEnum):
    mjOBJ_UNKNOWN = ...
    mjOBJ_BODY = ...
    mjOBJ_XBODY = ...
    mjOBJ_JOINT = ...
    mjOBJ_DOF = ...
    mjOBJ_GEOM = ...
    mjOBJ_SITE = ...
    mjOBJ_CAMERA = ...
    mjOBJ_LIGHT = ...
    mjOBJ_FLEX = ...
    mjOBJ_MESH = ...
    mjOBJ_SKIN = ...
    mjOBJ_HFIELD = ...
    mjOBJ_TEXTURE = ...
    mjOBJ_MATERIAL = ...
    mjOBJ_PAIR = ...
    mjOBJ_EXCLUDE = ...
    mjOBJ_EQUALITY = ...
    mjOBJ_TENDON = ...
    mjOBJ_ACTUATOR = ...
    mjOBJ_SENSOR = ...
    mjOBJ_NUMERIC = ...
    mjOBJ_TEXT = ...
    mjOBJ_TUPLE = ...
    mjOBJ_KEY = ...
    mjOBJ_PLUGIN = ...
    mjOBJ_FRAME = ...

class mjtFontScale(IntEnum):
    mjFONTSCALE_50 = ...
    mjFONTSCALE_100 = ...
    mjFONTSCALE_150 = ...
    mjFONTSCALE_200 = ...
    mjFONTSCALE_250 = ...
    mjFONTSCALE_300 = ...

class mjtGridPos(IntEnum):
    mjGRID_TOPLEFT = ...
    mjGRID_TOPRIGHT = ...
    mjGRID_BOTTOMLEFT = ...
    mjGRID_BOTTOMRIGHT = ...

class mjtFramebuffer(IntEnum):
    mjFB_WINDOW = ...
    mjFB_OFFSCREEN = ...

class mjtDepthMap(IntEnum):
    mjDEPTH_ZERONEAR = ...
    mjDEPTH_ZEROFAR = ...

class mjtRndFlag(IntEnum):
    mjRND_SHADOW = ...
    mjRND_WIREFRAME = ...
    mjRND_REFLECTION = ...
    mjRND_ADDITIVE = ...
    mjRND_SKYBOX = ...
    mjRND_FOG = ...
    mjRND_HAZE = ...
    mjRND_SEGMENT = ...
    mjRND_IDCOLOR = ...
    mjRND_CULL_FACE = ...

class mjtCamera(IntEnum):
    mjCAMERA_FREE = ...
    mjCAMERA_TRACKING = ...
    mjCAMERA_FIXED = ...
    mjCAMERA_USER = ...

class mjtCatBit(IntEnum):
    mjCAT_STATIC = ...
    mjCAT_DYNAMIC = ...
    mjCAT_DECOR = ...
    mjCAT_ALL = ...

class mjtState(IntEnum):
    mjSTATE_TIME = ...
    mjSTATE_QPOS = ...
    mjSTATE_QVEL = ...
    mjSTATE_ACT = ...
    mjSTATE_WARMSTART = ...
    mjSTATE_CTRL = ...
    mjSTATE_QFRC_APPLIED = ...
    mjSTATE_XFRC_APPLIED = ...
    mjSTATE_EQ_ACTIVE = ...
    mjSTATE_MOCAP_POS = ...
    mjSTATE_MOCAP_QUAT = ...
    mjSTATE_USERDATA = ...
    mjSTATE_PLUGIN = ...
    mjSTATE_PHYSICS = ...
    mjSTATE_FULLPHYSICS = ...
    mjSTATE_USER = ...
    mjSTATE_INTEGRATION = ...

class mjtEq(IntEnum): ...

class mjtGeom(IntEnum):
    mjGEOM_PLANE = 0
    mjGEOM_HFIELD = 1
    mjGEOM_SPHERE = 2
    mjGEOM_CAPSULE = 3
    mjGEOM_ELLIPSOID = 4
    mjGEOM_CYLINDER = 5
    mjGEOM_BOX = 6
    mjGEOM_MESH = 7
    mjGEOM_SDF = 8

    mjNGEOMTYPES = 9

    mjGEOM_ARROW = 100
    mjGEOM_ARROW1 = 101
    mjGEOM_ARROW2 = 102
    mjGEOM_LINE = 103
    mjGEOM_LINEBOX = 104
    mjGEOM_FLEX = 105
    mjGEOM_SKIN = 106
    mjGEOM_LABEL = 107
    mjGEOM_TRIANGLE = 108

    mjGEOM_NONE = 1001

class mjtJoint(IntEnum): ...
class mjtIntegrator(IntEnum): ...
class mjtCone(IntEnum): ...
class mjtJacobian(IntEnum): ...
class mjtSolver(IntEnum): ...
class mjtEnableBit(IntEnum): ...
class mjtDisableBit(IntEnum): ...
class mjtSensor(IntEnum): ...
class mjtStage(IntEnum): ...
class mjtBias(IntEnum): ...
class mjtGain(IntEnum): ...
class mjtDyn(IntEnum): ...
class mjtTrn(IntEnum): ...
class mjtWrap(IntEnum): ...
class mjtConstraint(IntEnum): ...
class mjtCamLight(IntEnum): ...
class mjtTexture(IntEnum): ...
class mjtBuiltin(IntEnum): ...
class mjtMark(IntEnum): ...
class mjtLabel(IntEnum): ...
class mjtFrame(IntEnum): ...

class _NamedAccessor:
    id: int
    name: str
    def __getattr__(self, name: str) -> Any: ...

class MjOption:
    timestep: float
    apirate: float
    impratio: float
    tolerance: float
    ls_tolerance: float
    gravity: FloatArray
    wind: FloatArray
    magnetic: FloatArray
    density: float
    viscosity: float
    o_margin: float
    o_solref: FloatArray
    o_solimp: FloatArray
    o_friction: FloatArray
    integrator: int
    cone: int
    jacobian: int
    solver: int
    iterations: int
    ls_iterations: int
    noslip_iterations: int
    mpr_iterations: int
    disableflags: int
    enableflags: int
    disableactuator: IntArray
    sdf_initpoints: int
    sdf_iterations: int
    @property
    def _all_fields(self) -> tuple[str, ...]: ...
    @property
    def _float_fields(self) -> tuple[str, ...]: ...
    @property
    def _int_fields(self) -> tuple[str, ...]: ...
    @property
    def _floatarray_fields(self) -> tuple[str, ...]: ...
    def __copy__(self) -> MjOption: ...
    def __deepcopy__(self, memo: dict[Any, Any]) -> MjOption: ...
    def __getattr__(self, name: str) -> Any: ...

class MjVisualGlobal:
    offwidth: int
    offheight: int
    ellipsoidinertia: int
    fovy: float
    ipd: float
    azimuth: float
    elevation: float
    linewidth: float
    glow: float
    realtime: float
    @property
    def _all_fields(self) -> tuple[str, ...]: ...
    def __getattr__(self, name: str) -> Any: ...

class MjVisualQuality:
    shadowsize: int
    offsamples: int
    numslices: int
    numstacks: int
    numquads: int
    def __getattr__(self, name: str) -> Any: ...

class MjVisualHeadlight:
    active: int
    ambient: FloatArray
    diffuse: FloatArray
    specular: FloatArray
    def __getattr__(self, name: str) -> Any: ...

class MjVisualMap:
    stiffness: float
    stiffnessrot: float
    force: float
    torque: float
    alpha: float
    fogstart: float
    fogend: float
    znear: float
    zfar: float
    haze: float
    shadowclip: float
    shadowscale: float
    actuatortendon: float
    def __getattr__(self, name: str) -> Any: ...

class MjVisualScale:
    forcewidth: float
    contactwidth: float
    contactheight: float
    connect: float
    com: float
    camera: float
    light: float
    selectpoint: float
    jointlength: float
    jointwidth: float
    actuatorlength: float
    actuatorwidth: float
    framelength: float
    framewidth: float
    constraint: float
    slidercrank: float
    frustum: float
    def __getattr__(self, name: str) -> Any: ...

class MjVisualRgba:
    fog: FloatArray
    haze: FloatArray
    force: FloatArray
    inertia: FloatArray
    joint: FloatArray
    actuator: FloatArray
    actuatortendon: FloatArray
    com: FloatArray
    camera: FloatArray
    light: FloatArray
    selectpoint: FloatArray
    connect: FloatArray
    contactpoint: FloatArray
    contactforce: FloatArray
    contactfriction: FloatArray
    contacttorque: FloatArray
    constraint: FloatArray
    slidercrank: FloatArray
    crankbroken: FloatArray
    frustum: FloatArray
    bv: FloatArray
    bvactive: FloatArray
    def __getattr__(self, name: str) -> Any: ...

class MjVisual:
    global_: MjVisualGlobal
    quality: MjVisualQuality
    headlight: MjVisualHeadlight
    map: MjVisualMap
    scale: MjVisualScale
    rgba: MjVisualRgba
    def __copy__(self) -> MjVisual: ...
    def __deepcopy__(self, memo: dict[Any, Any]) -> MjVisual: ...
    def __getattr__(self, name: str) -> Any: ...

class MjStatistic:
    meaninertia: float
    meanmass: float
    meansize: float
    extent: float
    center: FloatArray
    def __getattr__(self, name: str) -> Any: ...

class MjrRect:
    left: int
    bottom: int
    width: int
    height: int
    def __init__(
        self, left: int = 0, bottom: int = 0, width: int = 0, height: int = 0
    ) -> None: ...

class MjvCamera:
    type: int
    fixedcamid: int
    trackbodyid: int
    lookat: FloatArray
    distance: float
    azimuth: float
    elevation: float
    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class MjvOption:
    label: int
    frame: int
    flags: BoolArray
    geomgroup: BoolArray
    sitegroup: BoolArray
    jointgroup: BoolArray
    tendongroup: BoolArray
    actuatorgroup: BoolArray
    flexgroup: BoolArray
    skingroup: BoolArray
    bvh_depth: int
    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class MjvPerturb:
    active: int
    select: int
    flexselect: int
    skinselect: int
    localmass: float
    scale: float
    refpos: FloatArray
    refquat: FloatArray
    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class MjvGeom:
    type: int
    dataid: int
    objtype: int
    objid: int
    category: int
    segid: int
    texcoord: int
    emission: float
    specular: float
    shininess: float
    reflectance: float
    pos: FloatArray
    mat: FloatArray
    size: FloatArray
    rgba: FloatArray
    label: str
    def __getattr__(self, name: str) -> Any: ...

class MjvScene:
    maxgeom: int
    ngeom: int
    geoms: Any
    flags: BoolArray
    def __init__(self, model: MjModel, maxgeom: int) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class MjvFigure:
    flg_barplot: bool
    flg_extend: bool
    flg_symmetric: bool
    flg_legend: bool
    flg_ticklabel: tuple[bool, bool]
    gridsize: tuple[int, int]
    gridrgb: FloatArray
    figurergba: FloatArray
    panergba: FloatArray
    legendrgba: FloatArray
    textrgb: FloatArray
    linergb: FloatArray
    range: FloatArray
    xformat: str
    yformat: str
    minwidth: int
    linepnt: IntArray
    linedata: FloatArray
    xaxisdata: FloatArray
    linename: Any
    xlabel: str
    title: str
    ylabel: str
    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class MjrContext:
    readDepthMap: int
    currentBuffer: int
    offWidth: int
    offHeight: int
    def __init__(self, model: MjModel, fontscale: int) -> None: ...
    def free(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class MjContact:
    dist: float
    pos: FloatArray
    frame: FloatArray
    includemargin: float
    friction: FloatArray
    solref: FloatArray
    solreffriction: FloatArray
    solimp: FloatArray
    dim: int
    geom1: int
    geom2: int
    efc_address: int
    def __getattr__(self, name: str) -> Any: ...

class MjModelMeshViews:
    faceadr: Int32Array
    facenum: Int32Array
    graphadr: Int32Array
    id: int
    name: str
    texcoordadr: Int32Array
    vertadr: Int32Array
    vertnum: Int32Array

    def __repr__(self) -> str: ...

class MjModelBodyViews(_NamedAccessor): ...
class MjModelJointViews(_NamedAccessor): ...
class MjModelGeomViews(_NamedAccessor): ...
class MjModelSiteViews(_NamedAccessor): ...
class MjModelCameraViews(_NamedAccessor): ...
class MjModelLightViews(_NamedAccessor): ...
class MjModelGenericViews(_NamedAccessor): ...
class MjDataBodyViews(_NamedAccessor): ...
class MjDataJointViews(_NamedAccessor): ...
class MjDataGeomViews(_NamedAccessor): ...
class MjDataSiteViews(_NamedAccessor): ...
class MjDataCameraViews(_NamedAccessor): ...
class MjDataLightViews(_NamedAccessor): ...
class MjDataGenericViews(_NamedAccessor): ...

class MjModel:
    nq: int
    nv: int
    nu: int
    na: int
    nbody: int
    njnt: int
    ngeom: int
    nsite: int
    ncam: int
    nlight: int
    nflex: int
    nmesh: int
    nskin: int
    nhfield: int
    ntex: int
    nmat: int
    npair: int
    nexclude: int
    neq: int
    ntendon: int
    nwrap: int
    nsensor: int
    nnumeric: int
    ntext: int
    ntuple: int
    nkey: int
    nplugin: int
    nuserdata: int
    opt: MjOption
    vis: MjVisual
    stat: MjStatistic

    body_parentid: IntArray
    body_rootid: IntArray
    body_weldid: IntArray
    body_mocapid: IntArray
    body_jntnum: IntArray
    body_jntadr: IntArray
    body_geomnum: IntArray
    body_geomadr: IntArray
    body_pos: FloatArray
    body_quat: FloatArray
    body_ipos: FloatArray
    body_iquat: FloatArray
    body_mass: FloatArray
    body_subtreemass: FloatArray

    jnt_type: IntArray
    jnt_qposadr: IntArray
    jnt_dofadr: IntArray
    jnt_bodyid: IntArray
    jnt_group: IntArray
    jnt_limited: IntArray
    jnt_actfrclimited: IntArray
    jnt_solref: FloatArray
    jnt_solimp: FloatArray
    jnt_pos: FloatArray
    jnt_axis: FloatArray
    jnt_stiffness: FloatArray
    jnt_range: FloatArray
    jnt_actfrcrange: FloatArray
    jnt_margin: FloatArray
    jnt_user: FloatArray

    geom_type: IntArray
    geom_contype: IntArray
    geom_conaffinity: IntArray
    geom_condim: IntArray
    geom_bodyid: IntArray
    geom_dataid: IntArray
    geom_group: IntArray
    geom_matid: IntArray
    geom_priority: IntArray
    geom_plugin: IntArray
    geom_pos: FloatArray
    geom_quat: FloatArray
    geom_size: FloatArray
    geom_aabb: FloatArray
    geom_rbound: FloatArray
    geom_solmix: FloatArray
    geom_solref: FloatArray
    geom_solimp: FloatArray
    geom_friction: FloatArray
    geom_margin: FloatArray
    geom_gap: FloatArray
    geom_fluid: FloatArray
    geom_rgba: FloatArray

    site_type: IntArray
    site_bodyid: IntArray
    site_matid: IntArray
    site_group: IntArray
    site_sameframe: IntArray
    site_pos: FloatArray
    site_quat: FloatArray
    site_size: FloatArray
    site_rgba: FloatArray

    cam_mode: IntArray
    cam_bodyid: IntArray
    cam_targetbodyid: IntArray
    cam_pos: FloatArray
    cam_quat: FloatArray
    cam_poscom0: FloatArray
    cam_pos0: FloatArray
    cam_mat0: FloatArray
    cam_fovy: FloatArray
    cam_ipd: FloatArray
    cam_resolution: IntArray
    cam_sensorsize: FloatArray
    cam_intrinsic: FloatArray

    light_mode: IntArray
    light_bodyid: IntArray
    light_targetbodyid: IntArray
    light_directional: IntArray
    light_castshadow: IntArray
    light_active: IntArray
    light_pos: FloatArray
    light_dir: FloatArray
    light_attenuation: FloatArray
    light_cutoff: FloatArray
    light_exponent: FloatArray
    light_ambient: FloatArray
    light_diffuse: FloatArray
    light_specular: FloatArray

    actuator_trntype: IntArray
    actuator_dyntype: IntArray
    actuator_gaintype: IntArray
    actuator_biastype: IntArray
    actuator_trnid: IntArray
    actuator_actadr: IntArray
    actuator_actnum: IntArray
    actuator_ctrllimited: IntArray
    actuator_forcelimited: IntArray
    actuator_actlimited: IntArray
    actuator_dynprm: FloatArray
    actuator_gainprm: FloatArray
    actuator_biasprm: FloatArray
    actuator_ctrlrange: FloatArray
    actuator_forcerange: FloatArray
    actuator_actrange: FloatArray
    actuator_gear: FloatArray
    actuator_cranklength: FloatArray
    actuator_acc0: FloatArray
    actuator_length0: FloatArray
    actuator_lengthrange: FloatArray

    sensor_type: IntArray
    sensor_datatype: IntArray
    sensor_needstage: IntArray
    sensor_objtype: IntArray
    sensor_objid: IntArray
    sensor_reftype: IntArray
    sensor_refid: IntArray
    sensor_dim: IntArray
    sensor_adr: IntArray
    sensor_cutoff: FloatArray
    sensor_noise: FloatArray
    sensor_user: FloatArray

    key_time: FloatArray
    key_qpos: FloatArray
    key_qvel: FloatArray
    key_act: FloatArray
    key_mpos: FloatArray
    key_mquat: FloatArray
    key_ctrl: FloatArray

    names: bytes

    @staticmethod
    def from_xml_string(
        xml: str | bytes, assets: dict[str, bytes] | None = ...
    ) -> MjModel: ...
    @staticmethod
    def from_xml_path(
        filename: str, assets: dict[str, bytes] | None = ...
    ) -> MjModel: ...
    @staticmethod
    def from_binary_path(
        filename: str, assets: dict[str, bytes] | None = ...
    ) -> MjModel: ...
    @staticmethod
    def _from_model_ptr(addr: int) -> MjModel: ...
    def body(self, name: str) -> MjModelBodyViews: ...
    def jnt(self, name: str) -> MjModelJointViews: ...
    def joint(self, name: str) -> MjModelJointViews: ...
    def geom(self, name: str) -> MjModelGeomViews: ...
    def site(self, name: str) -> MjModelSiteViews: ...
    def cam(self, name: str) -> MjModelCameraViews: ...
    def camera(self, name: str) -> MjModelCameraViews: ...
    def light(self, name: str) -> MjModelLightViews: ...
    def mesh(self, name: str | int) -> MjModelMeshViews: ...
    def skin(self, name: str) -> MjModelGenericViews: ...
    def hfield(self, name: str) -> MjModelGenericViews: ...
    def tex(self, name: str) -> MjModelGenericViews: ...
    def texture(self, name: str) -> MjModelGenericViews: ...
    def material(self, name: str) -> MjModelGenericViews: ...
    def pair(self, name: str) -> MjModelGenericViews: ...
    def exclude(self, name: str) -> MjModelGenericViews: ...
    def equality(self, name: str) -> MjModelGenericViews: ...
    def tendon(self, name: str) -> MjModelGenericViews: ...
    def actuator(self, name: str) -> MjModelGenericViews: ...
    def sensor(self, name: str) -> MjModelGenericViews: ...
    def numeric(self, name: str) -> MjModelGenericViews: ...
    def text(self, name: str) -> MjModelGenericViews: ...
    def tuple(self, name: str) -> MjModelGenericViews: ...
    def key(self, name: str) -> MjModelGenericViews: ...
    def plugin(self, name: str) -> MjModelGenericViews: ...
    def bind_scalar(self, spec: Any) -> Any: ...
    def bind(self, specs: Sequence[MjStruct] | MjStruct) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...

class MjData:
    time: float
    energy: FloatArray
    qpos: FloatArray
    qvel: FloatArray
    act: FloatArray
    qacc_warmstart: FloatArray
    plugin_state: FloatArray
    ctrl: FloatArray
    qfrc_applied: FloatArray
    xfrc_applied: FloatArray
    eq_active: BoolArray
    mocap_pos: FloatArray
    mocap_quat: FloatArray
    qacc: FloatArray
    act_dot: FloatArray
    userdata: FloatArray
    sensordata: FloatArray

    xpos: FloatArray
    xquat: FloatArray
    xmat: FloatArray
    xipos: FloatArray
    ximat: FloatArray
    xanchor: FloatArray
    xaxis: FloatArray
    geom_xpos: FloatArray
    geom_xmat: FloatArray
    site_xpos: FloatArray
    site_xmat: FloatArray
    cam_xpos: FloatArray
    cam_xmat: FloatArray
    light_xpos: FloatArray
    light_xdir: FloatArray
    subtree_com: FloatArray
    cdof: FloatArray
    cinert: FloatArray
    crb: FloatArray
    cvel: FloatArray
    cacc: FloatArray
    cfrc_int: FloatArray
    cfrc_ext: FloatArray

    qfrc_bias: FloatArray
    qfrc_spring: FloatArray
    qfrc_damper: FloatArray
    qfrc_gravcomp: FloatArray
    qfrc_fluid: FloatArray
    qfrc_passive: FloatArray
    qfrc_actuator: FloatArray
    qfrc_smooth: FloatArray
    qfrc_constraint: FloatArray
    qfrc_inverse: FloatArray

    actuator_length: FloatArray
    actuator_moment: FloatArray
    actuator_force: FloatArray
    ten_length: FloatArray
    ten_J: FloatArray
    wrap_xpos: FloatArray

    qM: FloatArray
    qLD: FloatArray
    qLDiagInv: FloatArray
    contact: Sequence[MjContact]
    efc_type: IntArray
    efc_id: IntArray
    efc_J: FloatArray
    efc_pos: FloatArray
    efc_margin: FloatArray
    efc_frictionloss: FloatArray
    efc_D: FloatArray
    efc_aref: FloatArray
    efc_force: FloatArray

    def __init__(self, model: MjModel) -> None: ...
    def body(self, name: str) -> MjDataBodyViews: ...
    def jnt(self, name: str) -> MjDataJointViews: ...
    def joint(self, name: str) -> MjDataJointViews: ...
    def geom(self, name: str) -> MjDataGeomViews: ...
    def site(self, name: str) -> MjDataSiteViews: ...
    def cam(self, name: str) -> MjDataCameraViews: ...
    def camera(self, name: str) -> MjDataCameraViews: ...
    def light(self, name: str) -> MjDataLightViews: ...
    def mesh(self, name: str) -> MjDataGenericViews: ...
    def skin(self, name: str) -> MjDataGenericViews: ...
    def hfield(self, name: str) -> MjDataGenericViews: ...
    def tex(self, name: str) -> MjDataGenericViews: ...
    def texture(self, name: str) -> MjDataGenericViews: ...
    def material(self, name: str) -> MjDataGenericViews: ...
    def pair(self, name: str) -> MjDataGenericViews: ...
    def exclude(self, name: str) -> MjDataGenericViews: ...
    def equality(self, name: str) -> MjDataGenericViews: ...
    def tendon(self, name: str) -> MjDataGenericViews: ...
    def actuator(self, name: str) -> MjDataGenericViews: ...
    def sensor(self, name: str) -> MjDataGenericViews: ...
    def numeric(self, name: str) -> MjDataGenericViews: ...
    def text(self, name: str) -> MjDataGenericViews: ...
    def tuple(self, name: str) -> MjDataGenericViews: ...
    def key(self, name: str) -> MjDataGenericViews: ...
    def plugin(self, name: str) -> MjDataGenericViews: ...
    def bind_scalar(self, spec: Any) -> Any: ...
    def bind(self, specs: Sequence[MjStruct] | MjStruct) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...

class MjsBody: ...
class MjsFrame: ...
class MjsGeom: ...
class MjsJoint: ...
class MjsLight: ...
class MjsMaterial: ...
class MjsSite: ...
class MjsMesh: ...
class MjsSkin: ...
class MjsTexture: ...
class MjsText: ...
class MjsTuple: ...
class MjsCamera: ...
class MjsFlex: ...
class MjsHField: ...
class MjsKey: ...
class MjsNumeric: ...
class MjsPair: ...
class MjsExclude: ...
class MjsEquality: ...
class MjsTendon: ...
class MjsSensor: ...
class MjsActuator: ...
class MjsPlugin: ...

class MjSpec:
    modelname: str
    assets: dict[str, bytes]
    @staticmethod
    def from_file(filename: str) -> MjSpec: ...
    @staticmethod
    def from_string(
        xml: str | bytes, assets: dict[str, bytes] | None = ...
    ) -> MjSpec: ...
    @staticmethod
    def from_zip(file: str | IO[bytes]) -> MjSpec: ...
    def compile(self) -> MjModel: ...
    def to_xml(self) -> str: ...
    def to_zip(self, file: str | IO[bytes]) -> None: ...
    def body(self, name: str) -> MjsBody | None: ...
    def joint(self, name: str) -> MjsJoint | None: ...
    def geom(self, name: str) -> MjsGeom | None: ...
    def site(self, name: str) -> MjsSite | None: ...
    def camera(self, name: str) -> MjsCamera | None: ...
    def light(self, name: str) -> MjsLight | None: ...
    def mesh(self, name: str) -> MjsMesh | None: ...
    def skin(self, name: str) -> MjsSkin | None: ...
    def hfield(self, name: str) -> MjsHField | None: ...
    def numeric(self, name: str) -> MjsNumeric | None: ...
    def text(self, name: str) -> MjsText | None: ...
    def tuple(self, name: str) -> MjsTuple | None: ...
    def pair(self, name: str) -> MjsPair | None: ...
    def exclude(self, name: str) -> MjsExclude | None: ...
    def equality(self, name: str) -> MjsEquality | None: ...
    def tendon(self, name: str) -> MjsTendon | None: ...
    def sensor(self, name: str) -> MjsSensor | None: ...
    def actuator(self, name: str) -> MjsActuator | None: ...
    def plugin(self, name: str) -> MjsPlugin | None: ...
    def __getattr__(self, name: str) -> Any: ...

mjMINVAL: float
HEADERS_DIR: str
PLUGINS_DIR: str
PLUGIN_HANDLES: list[Any]
__version__: str

def to_zip(spec: MjSpec, file: str | IO[bytes]) -> None: ...
def from_zip(file: str | IO[bytes]) -> MjSpec: ...
def mj_versionString() -> str: ...
def mju_standardNormal(rng: Any | None) -> float: ...
def mj_name2id(model: MjModel, objtype: int, name: str) -> int: ...
def mj_id2name(model: MjModel, objtype: int, objid: int) -> str | None: ...
def mj_step(model: MjModel, data: MjData, nstep: int = ...) -> None: ...
def mj_step1(model: MjModel, data: MjData) -> None: ...
def mj_step2(model: MjModel, data: MjData) -> None: ...
def mj_forward(model: MjModel, data: MjData) -> None: ...
def mj_inverse(model: MjModel, data: MjData) -> None: ...
def mj_resetData(model: MjModel, data: MjData) -> None: ...
def mj_resetDataKeyframe(model: MjModel, data: MjData, key: int) -> None: ...
def mjv_defaultFreeCamera(model: MjModel, camera: MjvCamera) -> None: ...
def mjv_updateScene(
    model: MjModel,
    data: MjData,
    option: MjvOption,
    perturb: MjvPerturb | None,
    camera: MjvCamera,
    catmask: int,
    scene: MjvScene,
) -> None: ...
def mjr_setBuffer(framebuffer: int, context: MjrContext) -> None: ...
def mjr_render(viewport: MjrRect, scene: MjvScene, context: MjrContext) -> None: ...
def mjr_readPixels(
    rgb: UInt8Array | None,
    depth: Float32Array | None,
    viewport: MjrRect,
    context: MjrContext,
) -> None: ...
def __getattr__(name: str) -> Any: ...
