from __future__ import annotations

from collections.abc import Callable
from contextlib import AbstractContextManager
from queue import Queue
from typing import Optional, TypeAlias

import numpy as np

from . import MjData, MjModel, MjrRect, MjvCamera, MjvFigure, MjvOption, MjvPerturb, MjvScene

CallbackType: TypeAlias = Callable[[MjModel, MjData], None]
LoaderType: TypeAlias = Callable[[], tuple[MjModel, MjData]]
KeyCallbackType: TypeAlias = Callable[[int], None]


class Handle:
    @property
    def cam(self) -> MjvCamera: ...
    @property
    def opt(self) -> MjvOption: ...
    @property
    def perturb(self) -> MjvPerturb: ...
    @property
    def user_scn(self) -> MjvScene | None: ...
    @property
    def m(self) -> MjModel | None: ...
    @property
    def d(self) -> MjData | None: ...
    @property
    def viewport(self) -> MjrRect | None: ...
    def set_figures(self, viewports_figures: tuple[MjrRect, MjvFigure] | list[tuple[MjrRect, MjvFigure]]) -> None: ...
    def clear_figures(self) -> None: ...
    def set_texts(self, texts: tuple[int | None, int | None, str | None, str | None] | list[tuple[int | None, int | None, str | None, str | None]]) -> None: ...
    def clear_texts(self) -> None: ...
    def set_images(self, viewports_images: tuple[MjrRect, np.ndarray] | list[tuple[MjrRect, np.ndarray]]) -> None: ...
    def clear_images(self) -> None: ...
    def close(self) -> None: ...
    def is_running(self) -> bool: ...
    def lock(self) -> AbstractContextManager[object]: ...
    def sync(self, state_only: bool = ...) -> None: ...
    def update_hfield(self, hfieldid: int) -> None: ...
    def update_mesh(self, meshid: int) -> None: ...
    def update_texture(self, texid: int) -> None: ...
    def __enter__(self) -> Handle: ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...


def launch(model: MjModel | None = ..., data: MjData | None = ..., *, loader: LoaderType | None = ..., show_left_ui: bool = ..., show_right_ui: bool = ...) -> None: ...
def launch_from_path(path: str) -> None: ...
def launch_passive(model: MjModel, data: MjData, *, key_callback: KeyCallbackType | None = ..., show_left_ui: bool = ..., show_right_ui: bool = ...) -> Handle: ...
